### ISSUE TITLE
User can add tags

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/code-journal#11]
## 💰 Motivation

A user should be able to group the entries by custom tags they add.

## 📐 Plan

Allow users to add custom tags on entries.

## ✅ Task List

- [ ] Add an icon that creates a tag when the user clicks it and place it below each entry
- [ ] When the create tag icon is clicked replace it with an input box
- [ ] Have the new tag being made scale with the text in the input box
- [ ] When the user presses enter the tag should become part of the page, the input box should disappear, and the create tag icon should reappear
- [ ] There should be an x on each tag that shows when the user hovers the tag in order to delete it
- [ ] Tags should have uniquely colored backgrounds
- [ ] Tags should wrap
