### ISSUE TITLE
User can change to mini entry view

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/code-journal#15]
## 💰 Motivation

A user should be able to get a glimpse of many of their entries at once.

## 📐 Plan

Allow users to change view to mini entry view from current view

## 🖼️ Wireframes

https://www.figma.com/file/xcpLDlmEKYZxJuEt3dOpUo/Untitled?node-id=0%3A1

## ✅ Task List

- [x] Add small entry view icon at the top of entries page
- [x] Add large view icon at the top of entries page
- [x] Add hover pseudo classes for the icons
- [x] When mini view icon is selected in mobile have entries shrink to full width with small image on the left and title/tags/notes on the right
- [x] When mini view icon is selected in desktop have entries in the same view as mobile but in columns
