### ISSUE TITLE
User can search entries

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/code-journal#9]
## 💰 Motivation

If a user wants to find a specific entry, they should be able to search for it.

## 📐 Plan

Allow users to search for an entry.

## ✅ Task List

- [x] Add a search box at the top of the page
- [x] Add an event listener that listens for changes to `'input'` in the search box
- [x] Make an event handler function that takes the `event.target.value` from the search box and checks the title or notes of each entry for that expression
- [x] If the expression matches an entries title or notes then keep it in DOM tree and remove any hidden class
- [x] If the expression does not match then give it a hidden class
